geocode_result= [
   {
      'address_components':[
         {
            'long_name':'Santa Perpètua de Mogoda',
            'short_name':'Santa Perpètua de Mogoda',
            'types':[
               'locality',
               'political'
            ]
         },
         {
            'long_name':'Barcelona',
            'short_name':'Barcelona',
            'types':[
               'administrative_area_level_2',
               'political'
            ]
         },
         {
            'long_name':'Catalonia',
            'short_name':'CT',
            'types':[
               'administrative_area_level_1',
               'political'
            ]
         },
         {
            'long_name':'Spain',
            'short_name':'ES',
            'types':[
               'country',
               'political'
            ]
         },
         {
            'long_name':'08130',
            'short_name':'08130',
            'types':[
               'postal_code'
            ]
         }
      ],
      'formatted_address':'08130 Santa Perpètua de Mogoda, Barcelona, Spain',
      'geometry':{
         'bounds':{
            'northeast':{
               'lat':41.5401987,
               'lng':2.1885282
            },
            'southwest':{
               'lat':41.5250704,
               'lng':2.1746506
            }
         },
         'location':{
            'lat':41.5353285,
            'lng':2.1821487
         },
         'location_type':'APPROXIMATE',
         'viewport':{
            'northeast':{
               'lat':41.5401987,
               'lng':2.1885282
            },
            'southwest':{
               'lat':41.5250704,
               'lng':2.1746506
            }
         }
      },
      'partial_match':True,
      'place_id':'ChIJ87B7Ble-pBIRssDMKFKbrE0',
      'types':[
         'locality',
         'political'
      ]
   }
]

print(geocode_result[0]['geometry']['location']['lat'])